- hosts: gentoo
  gather_facts: true
  become: yes

  vars:
    sync: yes
    deep: yes

  tasks:

  - name: update @world set
    community.general.portage:
      package: '@world'
      update: yes
      deep: "{{ deep }}"
      sync: "{{ sync }}"
