- hosts: gentoo
  gather_facts: false
  become: true

  vars:
    packages:
        - app-admin/eclean-kernel
        - app-admin/sudo
        - app-editors/neovim
        - app-misc/screen
        - app-portage/eix
        - app-portage/genlop
        - app-portage/gentoolkit # needed!!
        - app-shells/fish
        - app-text/tree
        - dev-vcs/git
        - net-dns/bind-tools
        - sys-process/htop
        # Add more packages here or pass them as parameters
        # e.g
        # ansible-playbook software.yml --extra-vars "packages=['app-containers/docker', 'app-misc/neofetch']"

  tasks:
    - name: Install software using portage
      community.general.portage:
        name: "{{ item }}"
        state: present
      loop: "{{ packages }}"
